var recipes = [
{
	"name": "Chicken Salad",
	"keywords": ["chicken", "salad"],
	"type": "Lunch",
	"time": "10 minutes",
	"servings": "2",
	"ingredients": ["1/2 cup mayo", "1 Tbsp lemon juice", "1/4 tsp ground black pepper", "2 cups chopped, cooked chicken", "1/2 cup blanched silvered almonds", "1 stalk celery, chopped"],
	"steps": ["1. Prep all of the salad ingredients and toss them together in a large bowl.", "2. Prepare the chicken salad dressing in a separate smaller bowl.", "3. Mix together the mayonnaise, preserves, and lemon juice.", "4. Taste for the proper balance of sweetness and acidity. The salad dressing should not be too sweet nor too sour. Add more preserves or lemon juice until you have reached the balance you want. Add salt and pepper to taste.", "5. Gently stir the dressing in with the chicken salad ingredients. Taste and add more salt and pepper if needed."],
},
{
	"name": "Vegan Meatball Subs",
	"keywords": ["vegan"],
	"type": "Dinner",
	"cost": "$6",
	"servings": "2",
	"ingredients": ["8 vegan meatballs", "1/4 cup marinara sauce", "2 hoagie rolls, sliced in half lengthwise", "1/4 cup grated vegan mozzarella"],
	"steps": ["1. Preheat the broiler to low.", "2. Heat the meatballs and the sauce in the microwaveor on the stovetop until warm.", "3. Place four meatballs on each hoagie roll, top with half of the marinara and grated soy cheese, and place on an aluminum foil-lined baking sheet.", "4. Place under the broiler until the bread is toasted and the soy cheese has started to melt, about 3 minutes"]
},
{
	"name": "Vegetarian Mug Spinach Ricotta Lasagna",
	"type": "Lunch",
	"time": "10 minutes",
	"servings": "1",
	"ingredients": ["1/2 fresh lasagna sheet", "2 1/2 cups roughly chopped baby spinach", "1/4 diced medium yellow bell pepper", "1/4 cup part-skim ricotta cheese","3 large finely chopped basil leaves", "1/4 teaspoon kosher salt", "1/8 teaspoon granulated garlic", "6 tablespoons tomato or pasta sauce", "1/3 cup shredded part-skim mozzarella"],
	"steps": ["1. Cut the lasagna sheet in half, and cut each strip in half again. Place the pasta sheets into a bowl, and pour very hot water in it, until it covers all the pieces.", "2. Chop the spinach and place it in a microwave-safe bowl. Cover the top with plastic wrap and poke a few holes. Microwave for 1 minute and let it rest.", "3. Grate the mozzarella while you wait for the spinach to cool.", "4. Mix the spinach with the ricotta, pepper, granulated garlic, and salt. Set mixture aside.", "5. Pour 2 tablespoons of pasta sauce at the bottom of the mug. Top with a piece of softened pasta sheet. Add some spinach mixture, 2 tablespoons of mozzarella, and a pasta sheet. Continue building the lasagna, ending with a layer of pasta sheet at the top. Sprinkle mozzarella over the pasta.", "6. Microwave everything for 1 minute 30 seconds. Check to see that the mozzarella is melted. If it isn't, comtinue microwaving at 15-second intervals.", "7. Serve immediately."],
},
{
  "name": "Avocado Cream Pasta",
  "type": "Dinner",
  "time": "15 minutes",
  "cost": "$5.60",
  "servings": "2-3",
  "ingredients": ["2 avocados, pitted and diced", "1 clove garlic, minced", "Juice of 1/2 lemon", "1/4 cup unsweetened soy milk", "1/4 cup water", "Salt, to taste", "Red pepper flakes, to taste", "4 halved cherry tomatoes as garnish (optional)", "2 cups cooked pasta"],
  "steps": ["1. Combine the avocados, garlic, and lemon juice in a food processor. As the mixture is blending, add the soy milk and then the water. Add more or less water depending on your desired consistency.", "2. Add salt and red pepper, to taste.", "3. Toss with your favorite cooked pasta and serve."],
},
{
  "name": "Sticky Rice",
  "type": "Dinner",
  "cost": "$4.17",
  "servings": "6",
  "ingredients": ["2 cups of uncooked rice", "Canned or frozen vegetables", "Soy sauce, to taste"],
  "steps": ["1. Steam your rice.", "2. Microwave your vegetables.", "3. Mix the vegetables, rice, and soy sauce together."],
},
{
  "name": "Black Beans and Rice",
  "type": "Dinner",
  "time": "30 minutes",
  "cost": "$4.79",
  "servings": "6",
  "ingredients": ["1 Tbsp. olive oil", "1 large onion, chopped", "2 cloves garlic, minced", "3/4 cup uncooked rice", "1-1/2 cups vegetable broth", "1 tsp. ground cumin", "1/4 tsp. cayenne pepper", "3-1/2 cups canned black beans, drained"],
  "steps": ["1. Heat your oil over medium heat.", "2. Add the onion and garlic and saute for 4 minutes.", "3. Add the rice and saute for another 2 minutes.", "4. Add in the vegetable broth, bring to a boil, lower the heat and cook for 20 minutes.", "5. Add the spices and black beans immediately before you serve."],
},
{
	"name": "Mug Macaroni and Cheese",
	"type": "Lunch",
	"time": "10 minutes",
	"servings": "1",
	"ingredients": ["1/3 cup pasta", "3/4 cup cold water", "4 tablespoons milk", "1/4 teaspoons cornstarch", "4 tablespoons grated cheddar cheese", "salt", "pepper"],
	"steps": ["1. In a large microwavable mug or large bowl add in the macaroni and the water. You need a large mug as the water will boil up.", "2. Microwave for roughly 3 ½ minutes. You want the pasta to be fully cooked.", "3. Pour off the remaining cooking water.", "4. Stir in the milk, cornstarch and shredded cheese and microwave for a final 60 seconds to create your sauce. Stir well, season with salt and pepper and enjoy."],
},
{
	"name": "Mug Egg Fried Rice (Gluten-Free)",
	"type": "Lunch",
	"time": "13 minutes",
	"servings": "1",
	"ingredients": ["2 cups cooked rice", "1 cup mixed vegetables", "2 large eggs", "2 tablespoons low-sodium tamari", "1 teaspoon sesame seed oil", "1 teaspoon granulated garlic", "1/2 teaspoon five-spice powder", "pinch of salt", "1 stalk of green onions", "sesame seeds for garnish"],
	"steps": ["1. Place a cup of rice in a large mug. Top with vegetables, enough to fill the mug to the top. Cover with microwave-safe plastic wrap. Puncture a few holes in the plastic wrap with a chopstick or a fork.", "2. Turn the power setting of your microwave to 8/10 and set timer to 1 minute.", "3. While rice is cooking, whisk 1 egg, 1 tablespoon tamari, 1/2 teaspoon sesame oil (if using), 1/2 teaspoon granulated garlic, 1/4 teaspoon five-spice powder, and a small pinch of salt together.", "4. Take the mug out of the microwave, remove plastic wrap, and pour in egg mixture. Use a fork or spoon to give everything a few stirs. Cover rice with plastic wrap again, and microwave rice at an 8/10 power setting for 1 minute 15 to 1 minute 30 seconds.", "5. Using a fork or a spoon, fluff up the rice by stirring the contents several times.", "6. Repeat steps 1 to 4 for the remaining ingredients. Enjoy!"],
},
{
	"name": "Vegan Green Smoothie",
	"type": "Breakfast",
	"time": "5 minutes",
	"servings": "2",
	"ingredients": ["2 cups spinach", "2 cups water", "1 cup mango", "1 cup pineapple", "2 frozen bananas"],
	"instructions": ["1. Tightly pack 2 cups of leafy greens in a measuring cup and then toss into blender.", "2. Add water and blend together until all leafy chunks are gone.", "3. Add mango, pineapple and bananas and blend again until smooth.", "4. Pour into a mason jar (or cute cup of your choice).", "5. Gulp or sip like a rawkstar!"]
},
{
	"name": "Vegan Avocado Toast Recipe with Lemon and Chile",
	"type": "Breakfast",
	"time": "10 minutes",
	"servings": "2-4",
	"ingredients": ["2 ripe avocados", "2 slices of toasted bread", "1 teaspoon grated lemon zest juice of 1 lemon olive oil, for drizzling", " sea salt and chile flakes for sprinkling"],
	"instructions": ["1. Divide the avocado in half, remove the pit and carefully remove the skin.", "2. Slice the avocado into thin boats. ", "3. Divide the toast on a plate and spread the avocado, salt, chile, lemon zest, lemon juice, and drizzle a little oil over the top.", "4. Ready to serve!"],
},
{
	"name": "Mug Chicken Pot Pie",
	"type": "Lunch",
	"time": "25 minutes",
	"servings": "1",
	"ingredients": ["1/2 tablespoon Earth Balance Original Buttery Spread", "1/2 cup chopped mixed vegetables", "1/2 tablespoon flour", "2 tablespoons skim milk", "2 tablespoons chicken stock", "1/2 cooked chicken breast, cut into small pieces", "3 spears cooked asparagus, cut into small pieces", "4 sheets filo", "Low-calorie cooking spray", "1 teaspoon chopped fresh parsley"],
	"steps": ["1. Preheat the oven to 400°F.", "2. Microwave the margarine and mixed vegetables in a microwave- or oven-safe mug for 1 minute, or until the butter has melted.", "3. Add in the flour and stir until a paste has formed. Then stir in the skim milk and chicken stock.", "4. Add the chicken and asparagus to the mug and stir to combine. Season with salt and pepper.", "5. Cut out 4 squares of filo from 1 sheet, making sure each square is slightly larger then the top of the mug. Spray each square with cooking spray as you stack the sheets on top of the mug.", "6. Place the mug in the oven and bake for 10-15 minutes until the filo is flaky and golden in color.", "7. Sprinkle with parsley and serve immediately."],
},
{
	"name": "Vegan Yogurt Parfait",
  "type": "Breakfast",
  "time": "15 minutes",
  "servings": "2",
  "ingredients": ["1 6- to 8-ounce container of vanilla, lemon, or piña colada nondairy yogurt (coconut or other)", "1 cup fresh fruit", "Grated semi-sweet chocolate, toasted sliced almonds, or granola for topping"],
  "steps": ["1. Use a medium size tumbler or parfait cups and for each serving, layer 1/4 cup each of yogurt and fruit in the parfait dish.", "2. Repeat each layer, then do the same for the other parfaits.", "3. Sprinkle with the topping of choice, and serve."],
},
{
  "name": "Classic BLT Sandwich",
  "type": "Lunch",
  "time": "5 minutes",
  "servings": "1",
  "ingredients": ["2 slices white sandwich bread, toasted", "1 teaspoon unsalted, room temperature butter", "1 to 2 romain or iceberg lettuce leaves", "1 vine ripened tomato, sliced 1/4 inch thick", "3 to 4 basil leaves", "2 slices thickly cut bacon, cooked", "1/2 cup Homemade Mayonnaise", "Coarse salt and freshly ground pepper"],
  "steps": ["1. Spread one side of one slice of toast with butter.", "2. Arrange lettuce on top, along with tomato and basil. Season with salt and pepper.", "3. Top with bacon.", "4. Spread remaining slice of toast with mayonnaise; place mayonnaise side down to form a sandwich and cut on the diagonal. Serve immediately."],
},
{
	"name": "Vegetarian Mug Spinach Ricotta Lasagna",
	 "type": "Lunch",
	 "time": "10 minutes",
	 "servings": "1",
	 "ingredients": ["1/2 fresh lasagna sheet", "2 1/2 cups roughly chopped baby spinach", "1/4 diced medium yellow bell pepper", "1/4 cup part-skim ricotta cheese","3 large finely chopped basil leaves", "1/4 teaspoon kosher salt", "1/8 teaspoon granulated garlic", "6 tablespoons tomato or pasta sauce", "1/3 cup shredded part-skim mozzarella"],
	 "steps": ["1. Cut the lasagna sheet in half, and cut each strip in half again. Place the pasta sheets into a bowl, and pour very hot water in it, until it covers all the pieces.", "2. Chop the spinach and place it in a microwave-safe bowl. Cover the top with plastic wrap and poke a few holes. Microwave for 1 minute and let it rest.", "3. Grate the mozzarella while you wait for the spinach to cool.", "4. Mix the spinach with the ricotta, pepper, granulated garlic, and salt. Set mixture aside.", "5. Pour 2 tablespoons of pasta sauce at the bottom of the mug. Top with a piece of softened pasta sheet. Add some spinach mixture, 2 tablespoons of mozzarella, and a pasta sheet. Continue building the lasagna, ending with a layer of pasta sheet at the top. Sprinkle mozzarella over the pasta.", "6. Microwave everything for 1 minute 30 seconds. Check to see that the mozzarella is melted. If it isn't, comtinue microwaving at 15-second intervals.", "7. Serve immediately."],
},
{
	"name": "Mug Pizza",
	"type": "Lunch",
	"time": "6 minutes",
	"servings": "1",
	"ingredients": ["4 tablespoons all purpose flour", "⅛ teaspoon baking powder", "1/16 teaspoon baking soda", "⅛ teaspoon salt", "3 tablespoons milk", "1 tablespoon olive oil", "1 tablespoon marinara sauce", "1 generous tablespoon shredded mozzarella cheese", "5 mini pepperoni", "½ teaspoon dried Italian herbs (basil or oregano will work)"],
	"steps": ["1. Mix the flour, baking powder, baking soda and salt together in a microwavable mug", "2. Add in the milk and oil with mix together. There might be some lump but that is ok", "3. Spoon on the marinara sauce and spread it around the surface of the batter", "4. Sprinkle on the cheese, pepperoni and dried herbs", "5. Microwave for 1 minute 10-20 seconds, or until it rises up and the topping are bubbling"],
},
{
	"name": "Chicken Quesadillas",
	"type": "Lunch",
	"time": "15 minutes",
	"servings": "2",
	"ingredients": ["2 teaspoons canola oil, divided", "4, 10-inch flour tortillas", "2 cups shredded rotisserie chicken", "2 cups shredded cheddar cheese"],
	"steps": ["1. Heat 1 tsp. of the oil in a large frying pan over medium heat", "2. While the pan is heating, assemble the quesadillas. Sprinkle 1/2 cup of chicken over half of each tortilla. Top with 1/2 cup of cheese. Fold in half.", "3. Place one quesadilla at a time in the skillet. Let it cook 2 minutes until golden brown on one side.", "4. Flip with tongs. Cook another 2 minutes until cheese is melted and the quesadilla is brown on the other side. Remove to a plate.", "5. Repeat with remaining quesadillas."],
},
{
	"name": "Vegan Sushi Bowl",
	"type": "Lunch",
	"time": "15 minutes",
	"servings": "2",
	"ingredients": ["1 cup Sushi Rice (or other short-grain rice)", "1 cup water", "2 tablespoon Rice Wine Vinegar", "2 teaspoon natural cane sugar", "pinch salt", "1/2 cup each: Carrots, cucumber, avocado, and pepper", "soy sauce and toasted sesame seeds (optional)"],
	"steps": ["1. Place rice and water in steamer and set to cook.", "2. While rice is cooking, whisk together vinegar, sugar and salt.", "3. Once rice is done, stir in vinegar mixture.", "4. You may serve this rice warm or cold, then top with veggies (you can also add soy sauce and tpasted sesame seeds on top!)"],
},
{
	"name": "Savory Microwave Breakfast Mug",
	"type": "Breakfast",
	"time": "5 minutes",
	"ingredients": ["1 cup stale bread pieces*","1/4 cup pre-cooked chopped meat", "1/4 cup finely chopped vegetables", "2 Tbsp shredded cheese", "1 Tbsp butter", "3 Tbsp milk", "1 large egg", "Pinch of salt and pepper"],
	"steps": ["1. Tear or cut the bread into 1/2-inch pieces. Chop the meat and vegetables into small pieces. Shred the cheese.", "2. Add the butter to the bottom of a large mug (10-12oz.) and microwave on high for 20 seconds or until it is fully melted. Whisk in the milk, egg, salt, and pepper with a fork.", "3. Stir the meat, vegetables, and cheese into the milk and egg mixture first, then gently fold in the bread cubes until they are fully saturated.", "4. Let the mug sit for one minute to fully absorb the liquid, then microwave on high for about 90 seconds, or until the center is solid and it has begun to pull away from the mug around the edges. Serve hot."],
},
{
    "name": "Vegan Hash Browns" ,
		"keywords": ["vegan", "hash", "brown"],
    "type": "Breakfast",
    "time": "30 minutes",
    "cost": "$5",
    "ingredients": ["1 large russet potatoes", "2 Tbsp cooking oil", "Seasoning salt to taste"],
    "steps": ["1. Peel the potatoes, if desired. Use a large-holed cheese grater or food processor to shred the potatoes. Place the potatoes in a colander and rinse well, or until the water runs clear. Let the potatoes drain.", "2. Squeeze the potatoes of their excess water by pressing against the side of the colander or squeezing in your fist. Or, place the potatoes in a clean, lint-free dish towel, roll them up, then press to remove excess moisture.", "3. Heat a large cast iron or non-stick skillet over medium heat. Once hot, add a tablespoon of cooking oil and spread the oi, l over the surface. Add about 1/3 of the shredded potatoes. Let the potatoes fry, until deeply golden brown on the bottom (3-5 minutes). Season lightly with seasoning salt.","4. Flip the potatoes and drizzle additional oil if needed. Let the potatoes cook on the second side without disturbing until golden brown and crispy again. Season lightly.", "5. Cook until the ratio of brown and white is to your liking"],
	},
	{
		"name": "Microvwave Mug Toast",
		"type": "Breakfast",
		"time": "5 minutes",
		"cost": "$7",
		"ingredients": ["1 tsp butter", "3 Tbsp whole milk", "1 tsp maple syrup", "1/4 tsp cinnamon", "1/4 tsp vanilla extract", "Pinch ground nutmeg"]
	}
];
